baseURL = 'https://blakeanneberg.com/'
languageCode = 'en-us'
title = 'BlakeAnneberg.com'
 
theme = 'PaperMod'
paginate = 5
enableEmoji = true
mainsections = [ "posts", "papermod" ]


[[menu.main]]
identifier = "about.md"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "archives.md"
name = "Archives"
url = "/archives/"
weight = 20


[[menu.main]]
identifier = "InTheHyperloop"
name = "InTheHyperloop.com"
url = "https://www.inthehyperloop.com/"
weight = 30

[[menu.main]]
identifier = "CoorieHome.com"
name = "CoorieHome.com"
url = "https://www.cooriehome.com/"
weight = 30

[[menu.main]]
identifier = "BSAConsulting.LLC"
name = "BSAConsulting.LLC"
url = "https://www.BSAConsulting.LLC/"
weight = 30

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 40

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 40


[params]
subtitle = 'BlakeAnneberg.com'
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true

  [params.homeInfoParams]
  Title = "Welcome"
  Content = """
ğŸ‘‹ Documenting what I learn and thoughts on what I might learn next.  

ğŸŒ± Hobbies: 
Swim/Bike/Run, gardening, space, sustainable strawbale construction 

ğŸ§‘ğŸ’» Iâ€™m currently learning alot about: nvim using Kickstart as my text editor and TMUX to manage my SSH session. The Online courses I am learning are Python/django, Go and Data Analitics and SQL for Data Science.

ğŸ’ï¸ğŸ’»  Tech Goals:
Iâ€™m looking to collaborate on creating a real time interactive webpage/app that can showcase a train/hyperloop system and journey for cargo and passangers.
Build an API and learn how to monitise APIs.
Project: Rasberry PI to become a air monotoring station with Python.

ğŸ—º Random fact: I love Civilization 1.
"""

  [[params.socialIcons]]
  name = "github"
  title = "View my projects on Github"
  url = "https://github.com/blakeanneberg"

  [[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/channel/blakeanneberg"

  [[params.socialIcons]]
  name = "tableau"
  title = "See my projects on Tableau"
  url = "https://public.tableau.com/app/profile/blake.a6866/vizzes"
